### ISSUE TITLE
Unused variable?

### ISSUE THREAD

**Issue by lucyewright** [fac-15/SELECTlunch#17]
do you need to declare this 'request' variable if you're never using it? or were you planning to use it at a later date?
<img width="376" alt="screenshot 2018-12-07 at 10 22 07" src="https://user-images.githubusercontent.com/40594944/49642134-17294e00-fa0a-11e8-9e9c-cb0456d00e38.png">

**Comment by martinbagshaw** [comment]
fs...

**Comment by martinbagshaw** [comment]
We definitely need the file server module in the handlers file. It does not work without it.
